# Generated by Django 6.0.5 on 2026-05-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_negocio',
            new_name='negocio',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_rol',
            new_name='rol',
        ),
    ]
