# Generated by Django 6.0.5 on 2026-08-13 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authentication.negocio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=50),
        ),
    ]
