# Generated by Django 6.0.5 on 2026-05-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_id_negocio_usuario_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo / Trabajando'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'En Vacaciones'), ('PERMISO', 'Permiso Médico / Licencia'), ('SUSPENDIDO', 'Suspendido Temporalmente'), ('DESPEDIDO', 'Despedido / Fuera de la Empresa')], default='ACTIVO'),
        ),
    ]
