# Generated by Django 6.0.5 on 2026-05-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='estado',
            field=models.CharField(choices=[('PRUEBA', 'Prueba'), ('ACTIVO', 'Activo'), ('PENDIENTE_PAGO', 'Pendiente de pago'), ('SUSPENDIDO', 'Falta de pago / infraccion'), ('INACTIVO', 'Inactivo / dado de baja')], default='PRUEBA'),
        ),
    ]
