# Generated by Django 6.0.5 on 2026-06-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=0, help_text='Duracion del servicio en minutos')),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='primer_apellido',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='id_negocio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segundo_apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada'), ('REAGENDADA', 'Reagendada'), ('NO_ASISTIO', 'Cliente no llegó'), ('NO_ATENDIDA', 'Cliente no fue atendido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
