# Generated by Django 6.0.5 on 2026-06-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_servicio_rename_apellido_cliente_primer_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cita_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reagendamiento', to='appointments.cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='appointments.servicio'),
        ),
    ]
