# Generated by Django 6.0.5 on 2026-06-28 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_cita_cita_origen_cita_id_servicio'),
        ('authentication', '0004_alter_negocio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='id_negocio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='authentication.negocio'),
            preserve_default=False,
        ),
    ]
